name    'erikwebb-drupal'
version '0.0.3'
source 'git://github.com/erikwebb/erikwebb-drupal.git'
author 'erikwebb'
license 'Apache License, Version 2.0'
summary 'Drupal Puppet Module'
description 'A Puppet module to quickly create a basic Drupal installation.'
project_page 'http://github.com/erikwebb/erikwebb-drupal'

dependency 'puppetlabs/stdlib'
dependency 'erikwebb/drush'
